version: "3"
services:
  mysql:
    build:
      context: ./docker/mysql
    platform: 'linux/amd64'
    volumes:
      - ./docker/mysql/sqls/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/log/:/var/log/mysql
      - db-data:/var/lib/mysql
    env_file:
      - ./.webservice.env
    networks:
      - default
    ports:
      - "3305:3306"
  fast_api:
    command: ["uvicorn", "app.views:app","--reload", "--host", "0.0.0.0", "--port", "8000"]
    build:
      context: ./
      dockerfile: ./docker/fastapi/Dockerfile
    volumes:
      - ./app/:/app
    env_file:
      - ./.webservice.env
    ports:
      - "8000:8000"
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./.webservice.env
    ports:
      - "8080:80"
    networks:
      - default
    volumes:
      - /sessions
volumes:
  db-data:
networks:
  default:
